### PR TITLE
raidboss: fix Double Style trigger

### LINKED ISSUE #671: raidboos: m6s Double Style Tether Tracker triggered at wrong place
### Description

R6S Double Style Tether Tracker is called during arrow line aoe at add phase and lighting spread

### Additional Details / Steps to Reproduce

During M6S fights, the trigger R6S Double Style Tether Tracker (Start ${dir1}, launch towards ${dir2}) is called wrongly  when there's arrow aoe (at the end of add phase and later during lightning spread).

In the emulater, the following line is matched to the trigger after the arrow aoe call in add phase. It seems the same tetherId is reused for the arrows. The name "Sweet Shot" should be filtered out maybe?

>   "trigger": {
      "id": "R6S Double Style Tether Tracker",
      "type": "Tether",
      "netRegex": {
        "targetId": "4[0-9A-Fa-f]{7}",
        "id": [
          "013F",
          "0140"
        ],
        "capture": true
      },

>    "matches": {
      "type": "35",
      "timestamp": "2025-04-13T23:25:24.4780000+02:00",
      "sourceId": "40024B8E",
      "source": "Sweet Shot",
      "targetId": "400247CC",
      "target": "Sugar Riot",
      "id": "013F"
    }

>   "logLine": {
    "offset": 429510,
    "invalid": false,
    "index": 41243,
    "networkLine": "35|2025-04-13T22:48:06.4080000+02:00|400241B3|Sweet Shot|40024004|Sugar Riot|0000|0000|013F|40024004|000F|0000|39ff3b97b1d073c2",
    "tzOffsetMillis": 7200000,
    "decEventStr": "35",
    "decEvent": 35,
    "hexEvent": "23",
    "timestamp": 1744577286408,
    "checksum": "39ff3b97b1d073c2",
    "convertedLine": "[22:48:06.408] Tether 23:400241B3:Sweet Shot:40024004:Sugar Riot:0000:0000:013F:40024004:000F:0000",
    "id": "400241B3",
    "name": "Sweet Shot",
    "targetId": "40024004",
    "targetName": "Sugar Riot",
    "tetherId": "013F"
  },

### Cactbot Module

Raidboss (alerts & timelines)

### Configuration Info

```
Plugin Name - Status - Version - Path
FFXIV_ACT_Plugin.dll - Enabled - 2.7.3.1 - <ACT Folder>\Plugins\FFXIV_ACT_Plugin.dll
OverlayPlugin.dll - Enabled - 0.19.51 - <ACT Folder>\Plugins\OverlayPlugin\OverlayPlugin.dll
CactbotOverlay.dll - Enabled - 0.34.3.0 - <ACT Folder>\Plugins\cactbot\cactbot\CactbotOverlay.dll
AntiAfkKick-ACT.dll - Disabled - 2.0.0.0 - <ACT Folder>\Plugins\AntiAfkKick-ACT.dll

Overlay Name - URL
RaidBoss - file:///<ACT Folder>/Plugins/cactbot/cactbot/ui/raidboss/raidboss.html
mini parse - https://bsides.github.io/horizoverlay/
mistake - file:///<ACT Folder>/Plugins/cactbot/cactbot/ui/oopsyraidsy/oopsyraidsy.html

Various Settings - Value
Game Language - English
Plugin Language - English
Machina Region - Global
Game Version - 2025.03.27.0000.0000
Screen Mode - Windowed
ACT Process Elevation - Elevated (Admin)
FFXIV Process Elevation - Elevated (Admin)
Hide Chat Log (for privacy) - False
Disable Combine Pets with Owner - False
Disable Damage Shield estimates - False
(DEBUG) Enable Debug Options - True
(DEBUG) Log all Network Packets - False
(DEBUG) Also Show 'Real' DoT Ticks - False
(DEBUG) Simulate Individual DoT Crits - False
(DEBUG) Graph Potency, not Damage - False
(DEBUG) Enable Benchmark Tab - False
Cactbot User Dir - <ACT Folder>\Plugins\cactbot\cactbot\user\
```

### Log & Screenshots

Image

[AAC Cruiserweight M2 (Savage)_20250413_231847.883_10m_wipe.log](https://github.com/user-attachments/files/19733910/AAC.Cruiserweight.M2.Savage._20250413_231847.883_10m_wipe.log)

### Confirmation

- [x] I reviewed <a href='/OverlayPlugin/cactbot/blob/main/docs/FAQ-Troubleshooting.md'> Common Issues and Workarounds</a> and verified that my settings are correct.
- [x] I used the search function to confirm this issue doesn't already exist.

### PR DESCRIPTION
**Pull request by xiashtra**
closes #671 

Also improves the callout for Taste of Fire/Taste of Thunder.

### CODE REVIEW

File: ui/raidboss/data/07-dt/raid/r6s.ts [hunk 1]
```diff
@@ -180,9 +180,10 @@ const triggerSet: TriggerSet<Data> = {
       run: (data, matches) => data.lastDoubleStyle = doubleStyleMap[matches.id],
     },
     {
+      // tether source is from the actor to the boss
       id: 'R6S Double Style Tether Tracker',
       type: 'Tether',
-      netRegex: { targetId: '4[0-9A-Fa-f]{7}', id: ['013F', '0140'], capture: true },
+      netRegex: { sourceId: '4[0-9A-Fa-f]{7}', id: ['013F', '0140'], capture: true },
```
Comment (valarnin) [inline ui/raidboss/data/07-dt/raid/r6s.ts:186]: IIRC I went with `targetId` here instead of `sourceId` to allow also matching against the normal/wing bomb tether at the end of desert phase (since `sourceId` entries are player IDs for that mechanic), but that's being handled by a different trigger now so it shouldn't matter.

**Review by valarnin — APPROVED** [review]

File: ui/raidboss/data/07-dt/raid/r6s.ts (hunk 1 above)
Comment (xiashtra) [reply ui/raidboss/data/07-dt/raid/r6s.ts:186]: I changed it here because like you said, we have another trigger handling the desert phase player tethers, and this one was collecting unnecessary data then.
